name: 'colslaue'
version: '1.0.0'
config-version: 2

profile: 'colslaue'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  colslaue:
    report_tables:
      +schema: report_tables
      +materialized: table

    source_data:
      +schema: source_data
      +materialized: table
